USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/samsung/a7ltechn/BoardConfigVendor.mk

BOARD_VENDOR := samsung
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8939
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := a7ltechn
TARGET_USE_QCOM_BIONIC_OPTIMIZATION := true

# Kernel
TARGET_PREBUILT_KERNEL := device/samsung/a7ltechn/kernel
BOARD_KERNEL_CMDLINE := console=null androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000 --tags_offset 0x01e00000 --dt device/samsung/a7ltechn/dt.img
KERNEL_EXFAT_MODULE_NAME := "exfat"

# fix this up by examining /proc/mtd on a running device
# Recovery
TARGET_RECOVERY_SCREEN_WIDTH := 1080
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TARGET_USES_QCOM_BSP := true
BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/samsung/a7ltechn/recovery/recovery_keys.c
BOARD_USE_CUSTOM_RECOVERY_FONT := \"fontcn46_28x73.h\"
#BOARD_USE_CUSTOM_RECOVERY_FONT := \"fonten44_26x71.h\"
BOARD_USES_MMCUTILS := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_RECOVERY_FSTAB := device/samsung/a7ltechn/recovery/recovery.fstab
RECOVERY_USE_MIGRATED_STORAGE := true
TARGET_RECOVERY_LCD_BACKLIGHT_PATH := \"/sys/class/leds/lcd-backlight/brightness\"
RECOVERY_USE_VIRTUAL_KEY := true
#BOARD_RECOVERY_SWIPE := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE

# Assert
TARGET_OTA_ASSERT_DEVICE := a7ltechn,SM-A7000

TARGET_QCOM_DISPLAY_VARIANT := caf-new
